[tools]
python = "3.14"

[env]
_.path = ["./venv/bin"]

[tasks.install]
description = "Создание venv и установка зависимостей"
run = [
    "python -m venv venv",
    "./venv/bin/pip install --upgrade pip",
    "./venv/bin/pip install -r requirements.txt"
]

[tasks.start]
description = "Запуск проекта"
depends = ["install"]
run = "python main.py"
